-- SQL Script to Drop the Database Schema

DROP TABLE IF EXISTS is_tp_orderHistory CASCADE;
DROP TABLE IF EXISTS is_tp_order CASCADE;
DROP TABLE IF EXISTS is_tp_bet CASCADE;
DROP TABLE IF EXISTS is_tp_auction CASCADE;
DROP TABLE IF EXISTS is_tp_transporter CASCADE;
DROP TABLE IF EXISTS is_tp_driver CASCADE;
DROP TABLE IF EXISTS is_tp_request CASCADE;
DROP TABLE IF EXISTS is_tp_cargo CASCADE;
DROP TABLE IF EXISTS is_tp_way CASCADE;
DROP TABLE IF EXISTS is_tp_userCompany CASCADE;
DROP TABLE IF EXISTS is_tp_user CASCADE;
DROP TABLE IF EXISTS is_tp_transport CASCADE;
DROP TABLE IF EXISTS is_tp_company CASCADE;
DROP TABLE IF EXISTS is_tp_customer CASCADE;
